export const packetPoolAbi = [
  {
    type: 'function',
    name: 'MIN_AMOUNT',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'DEFAULT_EXPIRY',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'createPool',
    inputs: [
      { name: 'poolId', type: 'bytes32' },
      { name: 'shares', type: 'uint8' },
      { name: 'memo', type: 'bytes32' },
      { name: 'token', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'createPoolWithExpiry',
    inputs: [
      { name: 'poolId', type: 'bytes32' },
      { name: 'shares', type: 'uint8' },
      { name: 'memo', type: 'bytes32' },
      { name: 'token', type: 'address' },
      { name: 'amount', type: 'uint256' },
      { name: 'duration', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'claim',
    inputs: [{ name: 'poolId', type: 'bytes32' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'refund',
    inputs: [{ name: 'poolId', type: 'bytes32' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getPool',
    inputs: [{ name: 'poolId', type: 'bytes32' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'creator', type: 'address' },
          { name: 'token', type: 'address' },
          { name: 'totalAmount', type: 'uint256' },
          { name: 'remainingAmount', type: 'uint256' },
          { name: 'totalShares', type: 'uint8' },
          { name: 'claimedShares', type: 'uint8' },
          { name: 'commitBlock', type: 'uint256' },
          { name: 'expiresAt', type: 'uint256' },
          { name: 'memo', type: 'bytes32' },
          { name: 'exists', type: 'bool' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getPoolClaims',
    inputs: [{ name: 'poolId', type: 'bytes32' }],
    outputs: [
      { name: 'claimers', type: 'address[]' },
      { name: 'amounts', type: 'uint256[]' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getClaimInfo',
    inputs: [
      { name: 'poolId', type: 'bytes32' },
      { name: 'claimIndex', type: 'uint8' },
    ],
    outputs: [
      { name: 'claimer', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'hasClaimed',
    inputs: [
      { name: '', type: 'bytes32' },
      { name: '', type: 'address' },
    ],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'PoolCreated',
    inputs: [
      { name: 'poolId', type: 'bytes32', indexed: true },
      { name: 'creator', type: 'address', indexed: true },
      { name: 'token', type: 'address', indexed: false },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'shares', type: 'uint8', indexed: false },
      { name: 'memo', type: 'bytes32', indexed: false },
      { name: 'expiresAt', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Claimed',
    inputs: [
      { name: 'poolId', type: 'bytes32', indexed: true },
      { name: 'claimer', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'claimIndex', type: 'uint8', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Refunded',
    inputs: [
      { name: 'poolId', type: 'bytes32', indexed: true },
      { name: 'creator', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  { type: 'error', name: 'PoolAlreadyExists', inputs: [] },
  { type: 'error', name: 'PoolNotFound', inputs: [] },
  { type: 'error', name: 'PoolFullyClaimed', inputs: [] },
  { type: 'error', name: 'PoolExpired', inputs: [] },
  { type: 'error', name: 'PoolNotExpired', inputs: [] },
  { type: 'error', name: 'AlreadyClaimed', inputs: [] },
  { type: 'error', name: 'InvalidShares', inputs: [] },
  { type: 'error', name: 'InvalidAmount', inputs: [] },
  { type: 'error', name: 'NotPoolCreator', inputs: [] },
  { type: 'error', name: 'NothingToRefund', inputs: [] },
  { type: 'error', name: 'TransferFailed', inputs: [] },
] as const
